# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0.xci
# IP: The module: 'minized_petalinux_axi_fifo_mm_s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_axi_fifo_mm_s_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0.xci
# IP: The module: 'minized_petalinux_axi_fifo_mm_s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_axi_fifo_mm_s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
