# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/minized_petalinux_pdm_filter_sysgen_0_0.xci
# IP: The module: 'minized_petalinux_pdm_filter_sysgen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/pdm_filter_sysgen_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/pdm_filter_sysgen_fir_compiler_v7_2_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/constrs/pdm_filter_sysgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_pdm_filter_sysgen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/minized_petalinux_pdm_filter_sysgen_0_0.xci
# IP: The module: 'minized_petalinux_pdm_filter_sysgen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/pdm_filter_sysgen_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/pdm_filter_sysgen_fir_compiler_v7_2_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filter_sysgen_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/constrs/pdm_filter_sysgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_pdm_filter_sysgen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
