#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2.2 (64-bit)
#
# Filename    : minized_petalinux.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Mar 31 10:44:32 +0100 2019
# SW Build 2348494 on Mon Oct  1 18:25:44 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: minized_petalinux.sh [-help]
# usage: minized_petalinux.sh [-lib_map_path]
# usage: minized_petalinux.sh [-noclean_files]
# usage: minized_petalinux.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'minized_petalinux.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_19 lib_pkg_v1_0_2 axi_iic_v2_0_20 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_19 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 xlconcat_v2_1_1 xlconstant_v1_1_5 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 xbip_utils_v3_0_9 c_reg_fd_v12_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_5 xbip_dsp48_addsub_v3_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 blk_mem_gen_v8_4_1 c_gate_bit_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 dist_mem_gen_v8_0_12 util_vector_logic_v2_0_1 axi_utils_v2_0_5 fir_compiler_v7_2_11 lib_fifo_v1_0_11 axi_fifo_mm_s_v4_1_14 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 proc_sys_reset_v5_0_12 axi_clock_converter_v2_1_16 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "minized_petalinux.sh - Script generated by export_simulation (Vivado v2018.2.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_wireless_mgr_0_0/sim/minized_petalinux_wireless_mgr_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/sim/minized_petalinux_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/sim/minized_petalinux_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/df5e/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/sim/minized_petalinux_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/e469/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/sim/minized_petalinux_axi_uart16550_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_processing_system7_0_0/sim/minized_petalinux_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconcat_0_0/sim/minized_petalinux_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconstant_1_0/sim/minized_petalinux_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xbar_0/sim/minized_petalinux_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/sim/minized_petalinux.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/sim/minized_user_dsp_picos_c_addsub_v12_0_i0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/sim/minized_user_dsp_picos_fifo_generator_i0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_mult_gen_v12_0_i0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_mult_gen_v12_0_i0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_mult_gen_v12_0_i0/sim/minized_user_dsp_picos_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/srl17e.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/srl33e.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/minized_user_dsp_picos_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/minized_user_dsp_picos.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/minized_user_dsp_picos_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/synth_reg.v" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl/convert_type.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/sim/minized_petalinux_minized_user_dsp_pic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/sim/minized_demodulate_blk_mem_gen_i0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/sim/minized_demodulate_blk_mem_gen_i1.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/sim/minized_demodulate_blk_mem_gen_i2.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/sim/minized_demodulate_blk_mem_gen_i3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i0/sim/minized_demodulate_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i1/sim/minized_demodulate_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i2/sim/minized_demodulate_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i3/sim/minized_demodulate_c_addsub_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i4/sim/minized_demodulate_c_addsub_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i5/sim/minized_demodulate_c_addsub_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i6/sim/minized_demodulate_c_addsub_v12_0_i6.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/sim/minized_demodulate_c_counter_binary_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i1/sim/minized_demodulate_c_counter_binary_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i2/sim/minized_demodulate_c_counter_binary_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i3/sim/minized_demodulate_c_counter_binary_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i4/sim/minized_demodulate_c_counter_binary_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i5/sim/minized_demodulate_c_counter_binary_v12_0_i5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/sim/minized_demodulate_dist_mem_gen_i0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/sim/minized_demodulate_dist_mem_gen_i1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i0/sim/minized_demodulate_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i1/sim/minized_demodulate_mult_gen_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i2/sim/minized_demodulate_mult_gen_v12_0_i2.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/f679/hdl/minized_demodulate_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/f679/hdl/minized_demodulate.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/sim/minized_petalinux_minized_demodulate_0_0.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ae4d/hdl/minizedspeakerpwm_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ae4d/hdl/minizedspeakerpwm.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedspeakerpwm_0_0/sim/minized_petalinux_minizedspeakerpwm_0_0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/minizedssbmodulator_c_addsub_v12_0_i0/sim/minizedssbmodulator_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/minizedssbmodulator_c_addsub_v12_0_i1/sim/minizedssbmodulator_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/minizedssbmodulator_c_addsub_v12_0_i2/sim/minizedssbmodulator_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/minizedssbmodulator_c_counter_binary_v12_0_i0/sim/minizedssbmodulator_c_counter_binary_v12_0_i0.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/c9bd/hdl/minizedssbmodulator_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/c9bd/hdl/minizedssbmodulator.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/sim/minized_petalinux_minizedssbmodulator_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minizedtonedetect_blk_mem_gen_i0/sim/minizedtonedetect_blk_mem_gen_i0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minizedtonedetect_c_addsub_v12_0_i0/sim/minizedtonedetect_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minizedtonedetect_mult_gen_v12_0_i0/sim/minizedtonedetect_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl/minizedtonedetect_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl/minizedtonedetect.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl/minizedtonedetect_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/sim/minized_petalinux_minizedtonedetect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_0/sim/minized_petalinux_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_0/sim/minized_petalinux_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconstant_2_0/sim/minized_petalinux_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_1/sim/minized_petalinux_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_2/sim/minized_petalinux_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_max11105_adc_0_0/max11105_adc_c_counter_binary_v12_0_i0/sim/max11105_adc_c_counter_binary_v12_0_i0.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/bbaf/hdl/max11105_adc_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/bbaf/hdl/max11105_adc.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_max11105_adc_0_0/sim/minized_petalinux_max11105_adc_0_0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_microphone_mgr_0_0/sim/minized_petalinux_microphone_mgr_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_11 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/sim/pdm_filter_sysgen_fir_compiler_v7_2_i0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/sim/pdm_filter_sysgen_fir_compiler_v7_2_i1.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/srl17e.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/srl33e.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/pdm_filter_sysgen_entity_declarations.vhd" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/0c67/hdl/pdm_filter_sysgen.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/sim/minized_petalinux_pdm_filter_sysgen_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_fifo_mm_s_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/99f9/hdl/axi_fifo_mm_s_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/sim/minized_petalinux_axi_fifo_mm_s_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_0/sim/minized_petalinux_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_0/sim/minized_petalinux_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1_clk_wiz.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_rst_clk_wiz_100M_1/sim/minized_petalinux_rst_clk_wiz_100M_1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_33M_0/sim/minized_petalinux_rst_ps7_0_33M_0.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_1/sim/minized_petalinux_axi_bram_ctrl_0_1.vhd" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_2/sim/minized_petalinux_axi_bram_ctrl_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_1/sim/minized_petalinux_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_2/sim/minized_petalinux_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_1/sim/minized_petalinux_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_2/sim/minized_petalinux_blk_mem_gen_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/e9a5/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_0/sim/minized_petalinux_axi_clock_converter_0_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_1/sim/minized_petalinux_axi_clock_converter_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_1_0/sim/minized_petalinux_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_3_0/sim/minized_petalinux_util_vector_logic_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_0_1/sim/minized_petalinux_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_cc_2/sim/minized_petalinux_auto_cc_2.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_cc_1/sim/minized_petalinux_auto_cc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/9d4a/hdl" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/b65a" +incdir+"$ref_dir/../../../../minized_petalinux.srcs/sources_1/bd/minized_petalinux/ipshared/d4ef/hdl" +incdir+"E:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_6/sim/minized_petalinux_auto_pc_6.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_5/sim/minized_petalinux_auto_pc_5.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_4/sim/minized_petalinux_auto_pc_4.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_3/sim/minized_petalinux_auto_pc_3.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_2/sim/minized_petalinux_auto_pc_2.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_1/sim/minized_petalinux_auto_pc_1.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_cc_0/sim/minized_petalinux_auto_cc_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_0/sim/minized_petalinux_auto_pc_0.v" \
    "$ref_dir/../../../bd/minized_petalinux/ip/minized_petalinux_auto_pc_7/sim/minized_petalinux_auto_pc_7.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.minized_petalinux xil_defaultlib.glbl -o minized_petalinux_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./minized_petalinux_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./minized_petalinux.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key minized_petalinux_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc minized_petalinux_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./minized_petalinux.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: minized_petalinux.sh [-help]\n\
Usage: minized_petalinux.sh [-lib_map_path]\n\
Usage: minized_petalinux.sh [-reset_run]\n\
Usage: minized_petalinux.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
