# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_petalinux_minized_user_dsp_pic_0_0.xci
# IP: The module: 'minized_petalinux_minized_user_dsp_pic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/minized_user_dsp_picos_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_c_addsub_v12_0_i0 || ORIG_REF_NAME==minized_user_dsp_picos_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/minized_user_dsp_picos_fifo_generator_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_fifo_generator_i0 || ORIG_REF_NAME==minized_user_dsp_picos_fifo_generator_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_mult_gen_v12_0_i0/minized_user_dsp_picos_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_mult_gen_v12_0_i0 || ORIG_REF_NAME==minized_user_dsp_picos_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/minized_user_dsp_picos_fifo_generator_i0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_fifo_generator_i0 || ORIG_REF_NAME==minized_user_dsp_picos_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/constrs/minized_user_dsp_picos.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_minized_user_dsp_pic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_petalinux_minized_user_dsp_pic_0_0.xci
# IP: The module: 'minized_petalinux_minized_user_dsp_pic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_c_addsub_v12_0_i0/minized_user_dsp_picos_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_c_addsub_v12_0_i0 || ORIG_REF_NAME==minized_user_dsp_picos_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/minized_user_dsp_picos_fifo_generator_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_fifo_generator_i0 || ORIG_REF_NAME==minized_user_dsp_picos_fifo_generator_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_mult_gen_v12_0_i0/minized_user_dsp_picos_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_mult_gen_v12_0_i0 || ORIG_REF_NAME==minized_user_dsp_picos_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/minized_user_dsp_picos_fifo_generator_i0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==minized_user_dsp_picos_fifo_generator_i0 || ORIG_REF_NAME==minized_user_dsp_picos_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/constrs/minized_user_dsp_picos.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_minized_user_dsp_pic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
