# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_petalinux_minized_demodulate_0_0.xci
# IP: The module: 'minized_petalinux_minized_demodulate_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/minized_demodulate_blk_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i0 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/minized_demodulate_blk_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i1 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/minized_demodulate_blk_mem_gen_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i2 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/minized_demodulate_blk_mem_gen_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i3 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i0/minized_demodulate_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i1/minized_demodulate_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i2/minized_demodulate_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i3/minized_demodulate_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i3 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i4/minized_demodulate_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i4 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i4} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i5/minized_demodulate_c_addsub_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i5 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i5} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i6/minized_demodulate_c_addsub_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i6 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i6} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/minized_demodulate_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i1/minized_demodulate_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i2/minized_demodulate_c_counter_binary_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i3/minized_demodulate_c_counter_binary_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i4/minized_demodulate_c_counter_binary_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i5/minized_demodulate_c_counter_binary_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/minized_demodulate_dist_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_dist_mem_gen_i0 || ORIG_REF_NAME==minized_demodulate_dist_mem_gen_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/minized_demodulate_dist_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_dist_mem_gen_i1 || ORIG_REF_NAME==minized_demodulate_dist_mem_gen_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i0/minized_demodulate_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i1/minized_demodulate_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i2/minized_demodulate_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/minized_demodulate_blk_mem_gen_i0_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/minized_demodulate_blk_mem_gen_i1_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/minized_demodulate_blk_mem_gen_i2_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/minized_demodulate_blk_mem_gen_i3_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/minized_demodulate_dist_mem_gen_i0_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/minized_demodulate_dist_mem_gen_i1_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/constrs/minized_demodulate.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_minized_demodulate_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_petalinux_minized_demodulate_0_0.xci
# IP: The module: 'minized_petalinux_minized_demodulate_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/minized_demodulate_blk_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i0 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/minized_demodulate_blk_mem_gen_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i1 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/minized_demodulate_blk_mem_gen_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i2 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/minized_demodulate_blk_mem_gen_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_blk_mem_gen_i3 || ORIG_REF_NAME==minized_demodulate_blk_mem_gen_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i0/minized_demodulate_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i1/minized_demodulate_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i2/minized_demodulate_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i3/minized_demodulate_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i3 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i4/minized_demodulate_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i4 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i4} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i5/minized_demodulate_c_addsub_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i5 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i5} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_addsub_v12_0_i6/minized_demodulate_c_addsub_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_addsub_v12_0_i6 || ORIG_REF_NAME==minized_demodulate_c_addsub_v12_0_i6} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i0/minized_demodulate_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i1/minized_demodulate_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i2/minized_demodulate_c_counter_binary_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i3/minized_demodulate_c_counter_binary_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i4/minized_demodulate_c_counter_binary_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_c_counter_binary_v12_0_i5/minized_demodulate_c_counter_binary_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==minized_demodulate_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/minized_demodulate_dist_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_dist_mem_gen_i0 || ORIG_REF_NAME==minized_demodulate_dist_mem_gen_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/minized_demodulate_dist_mem_gen_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_dist_mem_gen_i1 || ORIG_REF_NAME==minized_demodulate_dist_mem_gen_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i0/minized_demodulate_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i0 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i0} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i1/minized_demodulate_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i1 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i1} -quiet] -quiet

# IP: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_mult_gen_v12_0_i2/minized_demodulate_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_demodulate_mult_gen_v12_0_i2 || ORIG_REF_NAME==minized_demodulate_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/minized_demodulate_blk_mem_gen_i0_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/minized_demodulate_blk_mem_gen_i1_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/minized_demodulate_blk_mem_gen_i2_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/minized_demodulate_blk_mem_gen_i3_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/minized_demodulate_dist_mem_gen_i0_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/minized_demodulate_dist_mem_gen_i1_ooc.xdc

# XDC: e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/constrs/minized_demodulate.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_petalinux_minized_demodulate_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
