# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdl/Boards/MINIZED/minized_LEDs.xdc

# XDC: imports/hdl/Boards/bitstream_compression_enable.xdc

# XDC: imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc

# XDC: imports/hdl/Boards/MINIZED/minized_pins.xdc

# Block Designs: bd/minized_petalinux/minized_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux || ORIG_REF_NAME==minized_petalinux} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_wireless_mgr_0_0/minized_petalinux_wireless_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_wireless_mgr_0_0 || ORIG_REF_NAME==minized_petalinux_wireless_mgr_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_gpio_0_0 || ORIG_REF_NAME==minized_petalinux_axi_gpio_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_gpio_1_0 || ORIG_REF_NAME==minized_petalinux_axi_gpio_1_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_iic_0_0 || ORIG_REF_NAME==minized_petalinux_axi_iic_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_uart16550_0_0 || ORIG_REF_NAME==minized_petalinux_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_processing_system7_0_0/minized_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_processing_system7_0_0 || ORIG_REF_NAME==minized_petalinux_processing_system7_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_ps7_0_axi_periph_0/minized_petalinux_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_ps7_0_axi_periph_0 || ORIG_REF_NAME==minized_petalinux_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconcat_0_0/minized_petalinux_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconcat_0_0 || ORIG_REF_NAME==minized_petalinux_xlconcat_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_1_0/minized_petalinux_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_1_0 || ORIG_REF_NAME==minized_petalinux_xlconstant_1_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xbar_0/minized_petalinux_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xbar_0 || ORIG_REF_NAME==minized_petalinux_xbar_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_petalinux_minized_user_dsp_pic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_minized_user_dsp_pic_0_0 || ORIG_REF_NAME==minized_petalinux_minized_user_dsp_pic_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_petalinux_minized_demodulate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_minized_demodulate_0_0 || ORIG_REF_NAME==minized_petalinux_minized_demodulate_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_minizedspeakerpwm_0_0/minized_petalinux_minizedspeakerpwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_minizedspeakerpwm_0_0 || ORIG_REF_NAME==minized_petalinux_minizedspeakerpwm_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/minized_petalinux_minizedssbmodulator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_minizedssbmodulator_0_0 || ORIG_REF_NAME==minized_petalinux_minizedssbmodulator_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minized_petalinux_minizedtonedetect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_minizedtonedetect_0_0 || ORIG_REF_NAME==minized_petalinux_minizedtonedetect_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_0/minized_petalinux_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_util_vector_logic_0_0 || ORIG_REF_NAME==minized_petalinux_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_clk_wiz_0_0 || ORIG_REF_NAME==minized_petalinux_clk_wiz_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_0/minized_petalinux_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_0_0 || ORIG_REF_NAME==minized_petalinux_xlconstant_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_2_0/minized_petalinux_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_2_0 || ORIG_REF_NAME==minized_petalinux_xlconstant_2_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_1/minized_petalinux_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_util_vector_logic_0_1 || ORIG_REF_NAME==minized_petalinux_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_0_2/minized_petalinux_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_util_vector_logic_0_2 || ORIG_REF_NAME==minized_petalinux_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_max11105_adc_0_0/minized_petalinux_max11105_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_max11105_adc_0_0 || ORIG_REF_NAME==minized_petalinux_max11105_adc_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_microphone_mgr_0_0/minized_petalinux_microphone_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_microphone_mgr_0_0 || ORIG_REF_NAME==minized_petalinux_microphone_mgr_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/minized_petalinux_pdm_filter_sysgen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_pdm_filter_sysgen_0_0 || ORIG_REF_NAME==minized_petalinux_pdm_filter_sysgen_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==minized_petalinux_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_0/minized_petalinux_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_bram_ctrl_0_0 || ORIG_REF_NAME==minized_petalinux_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_0/minized_petalinux_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_blk_mem_gen_0_0 || ORIG_REF_NAME==minized_petalinux_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_clk_wiz_1 || ORIG_REF_NAME==minized_petalinux_clk_wiz_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_rst_clk_wiz_100M_1/minized_petalinux_rst_clk_wiz_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_rst_clk_wiz_100M_1 || ORIG_REF_NAME==minized_petalinux_rst_clk_wiz_100M_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_33M_0/minized_petalinux_rst_ps7_0_33M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_rst_ps7_0_33M_0 || ORIG_REF_NAME==minized_petalinux_rst_ps7_0_33M_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_1/minized_petalinux_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_bram_ctrl_0_1 || ORIG_REF_NAME==minized_petalinux_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_bram_ctrl_0_2/minized_petalinux_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_bram_ctrl_0_2 || ORIG_REF_NAME==minized_petalinux_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_1/minized_petalinux_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_0_1 || ORIG_REF_NAME==minized_petalinux_xlconstant_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_0_2/minized_petalinux_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_0_2 || ORIG_REF_NAME==minized_petalinux_xlconstant_0_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_1/minized_petalinux_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_blk_mem_gen_0_1 || ORIG_REF_NAME==minized_petalinux_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_2/minized_petalinux_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_blk_mem_gen_0_2 || ORIG_REF_NAME==minized_petalinux_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_0/minized_petalinux_axi_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_clock_converter_0_0 || ORIG_REF_NAME==minized_petalinux_axi_clock_converter_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_1/minized_petalinux_axi_clock_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_clock_converter_0_1 || ORIG_REF_NAME==minized_petalinux_axi_clock_converter_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_1_0/minized_petalinux_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_proc_sys_reset_1_0 || ORIG_REF_NAME==minized_petalinux_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_util_vector_logic_3_0/minized_petalinux_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_util_vector_logic_3_0 || ORIG_REF_NAME==minized_petalinux_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_0_1/minized_petalinux_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_proc_sys_reset_0_1 || ORIG_REF_NAME==minized_petalinux_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_cc_2/minized_petalinux_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_cc_2 || ORIG_REF_NAME==minized_petalinux_auto_cc_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_cc_1/minized_petalinux_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_cc_1 || ORIG_REF_NAME==minized_petalinux_auto_cc_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_6/minized_petalinux_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_6 || ORIG_REF_NAME==minized_petalinux_auto_pc_6} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_5/minized_petalinux_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_5 || ORIG_REF_NAME==minized_petalinux_auto_pc_5} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_4/minized_petalinux_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_4 || ORIG_REF_NAME==minized_petalinux_auto_pc_4} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_3/minized_petalinux_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_3 || ORIG_REF_NAME==minized_petalinux_auto_pc_3} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_2/minized_petalinux_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_2 || ORIG_REF_NAME==minized_petalinux_auto_pc_2} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_1/minized_petalinux_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_1 || ORIG_REF_NAME==minized_petalinux_auto_pc_1} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_cc_0/minized_petalinux_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_cc_0 || ORIG_REF_NAME==minized_petalinux_auto_cc_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_0/minized_petalinux_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_0 || ORIG_REF_NAME==minized_petalinux_auto_pc_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_7/minized_petalinux_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_7 || ORIG_REF_NAME==minized_petalinux_auto_pc_7} -quiet] -quiet

# XDC: bd/minized_petalinux/minized_petalinux_ooc.xdc
