# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/MINIZED_N3Z/minized_petalinux.cache/wt [current_project]
set_property parent.project_path E:/MINIZED_N3Z/minized_petalinux.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_repo_paths {
  e:/Github/hdl/IP/minized
  e:/hdl-minized/minized_speedway/IP/microphone_PDM
  p:/FPGADevelopment/Minized/MinizedSysgen
} [current_project]
set_property ip_output_repo e:/MINIZED_N3Z/minized_petalinux.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minizedtonedetect_blk_mem_gen_i0_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0_vivado.coe
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1_vivado.coe
read_vhdl -library xil_defaultlib E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/hdl/minized_petalinux_wrapper.vhd
add_files E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/minized_petalinux.bd
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_processing_system7_0_0/minized_petalinux_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/minized_user_dsp_picos_fifo_generator_i0/minized_user_dsp_picos_fifo_generator_i0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_user_dsp_pic_0_0/constrs/minized_user_dsp_picos.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i0/minized_demodulate_blk_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i1/minized_demodulate_blk_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i2/minized_demodulate_blk_mem_gen_i2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_blk_mem_gen_i3/minized_demodulate_blk_mem_gen_i3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i0/minized_demodulate_dist_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/minized_demodulate_dist_mem_gen_i1/minized_demodulate_dist_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minized_demodulate_0_0/constrs/minized_demodulate.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minizedspeakerpwm_0_0/constrs/minizedspeakerpwm.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minizedssbmodulator_0_0/constrs/minizedssbmodulator.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/minizedtonedetect_blk_mem_gen_i0/minizedtonedetect_blk_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_minizedtonedetect_0_0/constrs/minizedtonedetect.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_0_0/minized_petalinux_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_max11105_adc_0_0/constrs/max11105_adc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/pdm_filter_sysgen_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_pdm_filter_sysgen_0_0/constrs/pdm_filter_sysgen.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_fifo_mm_s_0_0/minized_petalinux_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_0/minized_petalinux_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_clk_wiz_1/minized_petalinux_clk_wiz_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_clk_wiz_100M_1/minized_petalinux_rst_clk_wiz_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_clk_wiz_100M_1/minized_petalinux_rst_clk_wiz_100M_1.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_clk_wiz_100M_1/minized_petalinux_rst_clk_wiz_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_33M_0/minized_petalinux_rst_ps7_0_33M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_33M_0/minized_petalinux_rst_ps7_0_33M_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_1/minized_petalinux_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_blk_mem_gen_0_2/minized_petalinux_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_0/minized_petalinux_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_0/minized_petalinux_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_0/minized_petalinux_axi_clock_converter_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_1/minized_petalinux_axi_clock_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_1/minized_petalinux_axi_clock_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_clock_converter_0_1/minized_petalinux_axi_clock_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_1_0/minized_petalinux_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_1_0/minized_petalinux_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_0_1/minized_petalinux_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_0_1/minized_petalinux_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_proc_sys_reset_0_1/minized_petalinux_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_2/minized_petalinux_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_2/minized_petalinux_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_2/minized_petalinux_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_1/minized_petalinux_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_1/minized_petalinux_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_1/minized_petalinux_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_6/minized_petalinux_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_5/minized_petalinux_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_4/minized_petalinux_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_3/minized_petalinux_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_2/minized_petalinux_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_1/minized_petalinux_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_0/minized_petalinux_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_0/minized_petalinux_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_cc_0/minized_petalinux_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_0/minized_petalinux_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_7/minized_petalinux_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/MINIZED_N3Z/minized_petalinux.srcs/sources_1/bd/minized_petalinux/minized_petalinux_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_LEDs.xdc
set_property used_in_implementation false [get_files E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_LEDs.xdc]

read_xdc E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/bitstream_compression_enable.xdc
set_property used_in_implementation false [get_files E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/bitstream_compression_enable.xdc]

read_xdc E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc
set_property used_in_implementation false [get_files E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc]

read_xdc E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_pins.xdc
set_property used_in_implementation false [get_files E:/MINIZED_N3Z/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top minized_petalinux_wrapper -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef minized_petalinux_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file minized_petalinux_wrapper_utilization_synth.rpt -pb minized_petalinux_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
